# Generated by Django 4.2.16 on 2024-09-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('AD', 'Администратор'), ('AN', 'Автор статей'), ('NU', 'Пользователь')], default='NU', max_length=2)),
            ],
        ),
    ]
